name: 'twitter_organic_source_integration_tests'
version: '0.3.0'
profile: 'integration_tests'
config-version: 2
vars:
  twitter_organic_source:
    twitter_account_history_identifer: "account_history"
    twitter_organic_tweet_report_identifer: "organic_tweet_report"
    twitter_tweet_identifer: "tweet"
    twitter_twitter_user_history_identifer: "twitter_user_history"
    twitter_organic_schema: twitter_organic_source_integration_tests
seeds:
  twitter_organic_source_integration_tests:
    tweet:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    organic_tweet_report:
      +column_types:
        organic_tweet_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
